namespace $ { $mol_style_attach( "milis/hello/hello.view.css",
 "/* Styling BEM-block by autogenerated attribute */\n[milis_hello] {\n\tdisplay: flex;\n\tflex-direction: column;\n\talign-items: center;\n\tbox-shadow: 0 0 0 1px var(--mol_theme_line);\n}\n\n/* Styling BEM-element by autogenerated attribute */\n[milis_hello_name] {\n\tflex-grow: 0;\n\tmargin: 1rem;\n\twidth: 14rem;\n}\n"
) }